# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/system.bd
# Block Designs: The module: 'system' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_rgb2lcd_0_2/system_rgb2lcd_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb2lcd_0_2 || ORIG_REF_NAME==system_rgb2lcd_0_2} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_dynclk_0_0/system_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dynclk_0_0 || ORIG_REF_NAME==system_axi_dynclk_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_5 || ORIG_REF_NAME==system_rst_ps7_0_100M_5} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_ps7_0_axi_periph_5/system_ps7_0_axi_periph_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_5 || ORIG_REF_NAME==system_ps7_0_axi_periph_5} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_ov5640_capture_data_0_0/system_ov5640_capture_data_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ov5640_capture_data_0_0 || ORIG_REF_NAME==system_ov5640_capture_data_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_ov5640_capture_data_1_0/system_ov5640_capture_data_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ov5640_capture_data_1_0 || ORIG_REF_NAME==system_ov5640_capture_data_1_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_1_0/system_v_vid_in_axi4s_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_1_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_osd_0_0/system_v_osd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_osd_0_0 || ORIG_REF_NAME==system_v_osd_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_5 || ORIG_REF_NAME==system_rst_ps7_0_100M_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_5 || ORIG_REF_NAME==system_rst_ps7_0_100M_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_1_0/system_v_vid_in_axi4s_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_ooc.xdc

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_osd_0_0/system_v_osd_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_osd_0_0 || ORIG_REF_NAME==system_v_osd_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/system_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/system.bd
# Block Designs: The module: 'system' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_rgb2lcd_0_2/system_rgb2lcd_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb2lcd_0_2 || ORIG_REF_NAME==system_rgb2lcd_0_2} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_dynclk_0_0/system_axi_dynclk_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dynclk_0_0 || ORIG_REF_NAME==system_axi_dynclk_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_5 || ORIG_REF_NAME==system_rst_ps7_0_100M_5} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_ps7_0_axi_periph_5/system_ps7_0_axi_periph_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_5 || ORIG_REF_NAME==system_ps7_0_axi_periph_5} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_ov5640_capture_data_0_0/system_ov5640_capture_data_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ov5640_capture_data_0_0 || ORIG_REF_NAME==system_ov5640_capture_data_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_ov5640_capture_data_1_0/system_ov5640_capture_data_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ov5640_capture_data_1_0 || ORIG_REF_NAME==system_ov5640_capture_data_1_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_1_0/system_v_vid_in_axi4s_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_1_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_osd_0_0/system_v_osd_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_osd_0_0 || ORIG_REF_NAME==system_v_osd_0_0} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_5 || ORIG_REF_NAME==system_rst_ps7_0_100M_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_5/system_rst_ps7_0_100M_5.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_5 || ORIG_REF_NAME==system_rst_ps7_0_100M_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_1_0/system_v_vid_in_axi4s_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_1_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0_ooc.xdc

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_v_osd_0_0/system_v_osd_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_osd_0_0 || ORIG_REF_NAME==system_v_osd_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: c:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: C:/Users/86182/Desktop/36_dual_ov5640_lcd/dual_ov5640_lcd.srcs/sources_1/bd/system/system_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system'. Do not add the DONT_TOUCH constraint.
